spring.application.name=vitalog-back

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vital_log
spring.datasource.username=postgres
spring.datasource.password=903856Lu%
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# CORS (Angular default port)
app.cors.allowed-origins=http://localhost:4200,http://localhost:3000

# Server
server.port=8080
